import React from 'react';
import "../css/about.css";

const ProductDescription = () => {
  const productData = [
    {
      title: "COCA-COLA",
      desc: "CARBONATED WATER. COCA-COLA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "COCA-COLA ZERO SUGAR",
      desc: "CARBONATED WATER. CONTAINS NON-CALORIC SWEETENER. THIS CARBONATED WATER CONTAINS AN ADMIXTURE OF SUCRALOSE AND ACESULFAME POTASSIUM. NOT RECOMMENDED FOR CHILDREN, PREGNANT AND LACTATING MOTHERS. TRADEMARK OWNER: THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "DIET COKE",
      desc: "CARBONATED WATER. CONTAINS AN ADMIXTURE OF ASPARTAME AND ACESULFAME POTASSIUM. NOT RECOMMENDED FOR PHENYLKETONURICS; FOR CHILDREN; PREGNANT AND LACTATING MOTHERS. COKE IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "SPRITE",
      desc: "CARBONATED WATER. SPRITE IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "THUMS UP",
      desc: "CARBONATED WATER. THUMS UP IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "LIMCA",
      desc: "CARBONATED WATER. ADDED LIME AND LEMON FLAVORS. 'LIME AND LEMONI' IS A CREATIVE EXPRESSION USED FOR LIMCA. LIMCA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "LIMCA SPORTZ",
      desc: "READY TO SERVE FRUIT BEVERAGE. *CONTAINS CARBOHYDRATE (INCLUDES 2.2% GLUCOSE) AND WITH ELECTROLYTES (SODIUM, POTASSIUM, CHLORIDE) WHICH HELP IN FASTER REHYDRATION THROUGH QUICK REPLACEMENT OF FLUID AND SALTS LOST IN SWEAT. LIMCA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "FANTA",
      desc: "CARBONATED WATER. FANTA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "FANTA APPLE DELITE",
      desc: "CARBONATED FRUIT BEVERAGE. CONTAINS 10.5% APPLE JUICE. CONTAINS NO FRUIT PIECES. \"BITE\" REFERS TO CRISPY, CRUNCHY TASTE OF APPLE. FANTA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT."
    },
    {
      title: "MAAZA ORIGINAL",
      desc: "READY TO SERVE FRUIT DRINK. MAAZA MANGO CONTAINS BLEND OF MANGO PULP INCLUDING ALPHONSO. MAAZA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY."
    },
    {
      title: "MAAZA AAM PANNA",
      desc: "READY TO SERVE FRUIT DRINK. MAAZA AAM PANNA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY"
    },
    {
      title: "SCHWEPPES BITTER LEMON, SCHWEPPES MINT MOJITO",
      desc: "CARBONATED WATER. SCHWEPPES IS A REGISTERED TRADEMARK OF EUROPEAN REFRESHMENTS UNLIMITED COMPANY. DRINK RESPONSIBLY."
    },
    {
      title: "CHARGED BY THUMS UP",
      desc: "CAFFEINATED BEVERAGE. *CHARGED BY THUMS UP HAS 2.8 TIMES CAFFEINE COMPARED TO REGULAR 250ml THUMS UP. CONTAINS ADDED BERRY FLAVOURS. HIGH CAFFEINE: 62.5mg/250ml. NOT RECOMMENDED FOR CHILDREN, PREGNANT OR LACTATING WOMEN."
    }
  ];

  return (
    <div className="info-container">
      <div className="info-list">
        {productData.map((product, index) => (
          <div key={index} className="info-item">
            <span className="product-title">{product.title}: </span>
            <span className="product-desc">{product.desc}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ProductDescription;